use sahana;
CREATE TABLE human(Human_name varchar(40),mobile_no bigint,aadhar_no bigint,height int,weight int,age double,skin_color varchar(21),hair_color varchar(30),inspiration varchar(38),pan_no bigint);
DESCRIBE human;
CREATE TABLE country(country_name varchar(30),country_population bigint,country_states int,country_capital varchar(5),country_teritoris int,country_malls bigint,country_tradition varchar(10),coutry_languages varchar(40),country_cities int,country_agriculture double);
DESC country;
CREATE TABLE cricket(no_of_teams int,participated_teams varchar(40),no_of_players int,no_of_batmans int,no_of_bowlers int,venue varchar(30),attended_crowd bigint,captain varchar(20),no_of_ballsused int,injury boolean);
DESCRIBE cricket;
CREATE TABLE brands_info(brand_name varchar(90),brand_types int,brand_price int,drand_value varchar(30),brand_place varchar(50),brand_ambassador varchar(20),brand_qualatiy double,brand_headquaters varchar(50),brand_noof_products bigint,brand_product_sales int);
DESCRIBE brands_info;
CREATE TABLE majestic(no_of_buses bigint,majestic_location varchar(40),drivers bigint,conductors bigint,cleaners int,destination varchar(50),no_of_kilomeaters bigint,acers_of_majestric int,types_of_buses int,color_of_bus varchar(30));
DESCRIBE majestic;
CREATE TABLE malls(no_of_branches int,no_of_products bigint,types_of_products bigint,saled_products int,customer_name varchar(40),customer_id bigint,new_products bigint,location varchar(40),branch_name varchar(20),mall_name varchar(45));
DESCRIBE malls;
CREATE TABLE education(education_type varchar(20),education_level int,education_related_jobs varchar(50),educated_people bigint,non_educated_people bigint,education_minister varchar(30),education_percentage double,education_standards varchar(70),education_noof_teachers int,education_board_types int);
DESCRIBE education;
CREATE TABLE food(food_name varchar(40),type_of_foods bigint,taste_of_food varchar(20),ingredients varchar(60),food_type_sweet boolean,food_type_spicy boolean,no_of_ingredients int,food_color varchar(20),food_acids boolean,price bigint);
DESCRIBE food;
CREATE TABLE hassan(no_of_malls bigint,no_of_places bigint,places_name varchar(40),no_of_busstops bigint,city_buses int,famous_places varchar(30),no_of_parks int,metro_available boolean,train_facility boolean,bus_price int);
DESCRIBE hassan;
CREATE TABLE river(river_name varchar(20),location varchar(30),acers double,water_temperature double,water_flow varchar(30),no_of_boats int,boat_sailorname varchar(20),no_of_boatsailors int,no_of_aqualife int,state_of_floating varchar(40));
DESCRIBE river;
ALTER TABLE brands_info ADD COLUMN brand_id int;
ALTER TABLE brands_info ADD COLUMN category varchar(40);
ALTER TABLE brands_info ADD COLUMN founding_year int;
ALTER TABLE brands_info ADD COLUMN website varchar(60);
ALTER TABLE brands_info ADD COLUMN description_brand varchar(63);
ALTER TABLE brands_info ADD COLUMN slogan varchar(70);
ALTER TABLE brands_info ADD COLUMN logo_url varchar(75);
ALTER TABLE brands_info ADD COLUMN ranking int;
ALTER TABLE brands_info ADD COLUMN awards varchar(40);
ALTER TABLE brands_info ADD COLUMN last_updated int;
SELECT * FROM brands_info;
ALTER TABLE brands_info DROP COLUMN ranking;
ALTER TABLE brands_info DROP COLUMN awards;
ALTER TABLE brands_info MODIFY COLUMN founding_year float;
ALTER TABLE brands_info MODIFY COLUMN brand_id double;
ALTER TABLE brands_info MODIFY COLUMN category float;
ALTER TABLE brands_info RENAME COLUMN founding_year TO updated_year;
ALTER TABLE brands_info RENAME COLUMN category TO group_no;
ALTER TABLE brands_info RENAME COLUMN website TO app;
ALTER TABLE brands_info RENAME COLUMN slogan TO motto;
ALTER TABLE brands_info RENAME COLUMN last_updated TO current_updated;
DESC brands_info;
ALTER TABLE hassan ADD COLUMN properties_price int;
ALTER TABLE hassan ADD COLUMN room_rent int;
ALTER TABLE hassan ADD COLUMN licensed_bike boolean;
ALTER TABLE hassan ADD COLUMN no_of_employees int;
ALTER TABLE hassan ADD COLUMN no_of_developers int;
ALTER TABLE hassan ADD COLUMN contact_number bigint;
ALTER TABLE hassan ADD COLUMN properties_availability boolean;
ALTER TABLE hassan ADD COLUMN property_type varchar(30); ;
ALTER TABLE hassan ADD COLUMN residencial_property boolean ;
ALTER TABLE hassan ADD COLUMN commercial_property boolean ;
ALTER TABLE hassan DROP COLUMN city_buses;
ALTER TABLE hassan DROP COLUMN bus_price;
select * from hassan;
ALTER TABLE hassan RENAME COLUMN train_facility TO buses_available;
ALTER TABLE hassan RENAME COLUMN metro_available TO bus_charges;
ALTER TABLE hassan RENAME COLUMN licensed_bike TO licensed_car;
ALTER TABLE hassan RENAME COLUMN contact_number TO alternative_number;
ALTER TABLE hassan RENAME COLUMN no_of_developers TO developer_name;
ALTER TABLE hassan MODIFY COLUMN commercial_property int;
ALTER TABLE hassan MODIFY COLUMN residencial_property int;
ALTER TABLE country ADD COLUMN country_id int;
ALTER TABLE country ADD COLUMN country_code varchar(20);
ALTER TABLE country ADD COLUMN country_area double;
ALTER TABLE country ADD COLUMN country_currency varchar(48);
ALTER TABLE country ADD COLUMN country_region varchar(10);
ALTER TABLE country ADD COLUMN country_time_zone varchar(56);
ALTER TABLE country ADD COLUMN country_gdp int;
ALTER TABLE country ADD COLUMN country_independence_date int;
ALTER TABLE country ADD COLUMN country_president varchar(47);
ALTER TABLE country ADD COLUMN country_flag_colour varchar(72);
SELECT * FROM country;
DESC country;
ALTER TABLE country DROP COLUMN country_gdp;
ALTER TABLE country DROP COLUMN country_population;
ALTER TABLE country MODIFY COLUMN country_time_zone int;
ALTER TABLE country MODIFY COLUMN country_area float;
ALTER TABLE country MODIFY COLUMN country_code int;
ALTER TABLE country RENAME COLUMN country_agriculture TO country_farming;
ALTER TABLE country RENAME COLUMN country_code TO country_pin;
ALTER TABLE country RENAME COLUMN country_time_zone TO country_latitude;
ALTER TABLE country RENAME COLUMN country_region TO country_place;
ALTER TABLE cricket ADD COLUMN player_name varchar(10);
ALTER TABLE cricket ADD COLUMN role_name varchar(10);
ALTER TABLE cricket ADD COLUMN batting_style boolean;
ALTER TABLE cricket ADD COLUMN bowling_style boolean;
ALTER TABLE cricket ADD COLUMN matches_played int;
ALTER TABLE cricket ADD COLUMN inninngs_played int;
ALTER TABLE cricket ADD COLUMN runs_scored bigint;
ALTER TABLE cricket ADD COLUMN centuries int;
ALTER TABLE cricket ADD COLUMN half_centuries int;
ALTER TABLE cricket ADD COLUMN no_of_wickets_taken int;
ALTER TABLE cricket DROP COLUMN participated_teams;
ALTER TABLE cricket DROP COLUMN captain;
ALTER TABLE cricket RENAME COLUMN injury TO injured_person;
ALTER TABLE cricket RENAME COLUMN role_name TO captain_name;
ALTER TABLE cricket RENAME COLUMN no_of_ballsused TO balls_used;
ALTER TABLE cricket RENAME COLUMN runs_scored TO scores;
ALTER TABLE cricket RENAME COLUMN no_of_wickets_taken TO wickets;
ALTER TABLE cricket MODIFY COLUMN batting_style boolean;
ALTER TABLE cricket MODIFY COLUMN bowling_style boolean;
ALTER TABLE cricket MODIFY COLUMN half_centuries bigint;
select * from cricket;
DESCRIBE cricket;
ALTER TABLE food ADD COLUMN serving_size int;
ALTER TABLE food ADD COLUMN category_name varchar(20);
ALTER TABLE food ADD COLUMN allerged_items boolean;
ALTER TABLE food ADD COLUMN nutritions varchar(30);
ALTER TABLE food ADD COLUMN preperation_method varchar(50);
ALTER TABLE food ADD COLUMN coocking_time float;
ALTER TABLE food ADD COLUMN recipe varchar(40);
ALTER TABLE food ADD COLUMN origin boolean;
ALTER TABLE food ADD COLUMN flavour varchar(20);
ALTER TABLE food ADD COLUMN brand varchar(10);
ALTER TABLE food DROP COLUMN food_type_sweet;
ALTER TABLE food DROP COLUMN food_type_sweet;
ALTER TABLE food RENAME COLUMN food_color TO color;
ALTER TABLE food RENAME COLUMN no_of_ingredients TO ingredient;
ALTER TABLE food RENAME COLUMN category_name TO category;
ALTER TABLE food RENAME COLUMN serving_size TO size;
ALTER TABLE food RENAME COLUMN preperation_method TO preperation_process;
ALTER TABLE food MODIFY COLUMN price int;
ALTER TABLE food MODIFY COLUMN nutritions boolean;
ALTER TABLE food MODIFY COLUMN coocking_time int;
select * from food;
DESCRIBE food;
ALTER TABLE human ADD COLUMN nick_name varchar(20);
ALTER TABLE human ADD COLUMN year_of_birth bigint;
ALTER TABLE human ADD COLUMN gender boolean;
ALTER TABLE human ADD COLUMN nationality varchar(10);
ALTER TABLE human ADD COLUMN occupation varchar(20);
ALTER TABLE human ADD COLUMN qualifications varchar(40);
ALTER TABLE human ADD COLUMN address varchar(40);
ALTER TABLE human ADD COLUMN blood_type varchar(20);
ALTER TABLE human ADD COLUMN emergency_contact bigint;
ALTER TABLE human ADD COLUMN marital_status boolean;
ALTER TABLE human DROP COLUMN aadhar_no;
ALTER TABLE human DROP COLUMN nick_name;
ALTER TABLE human RENAME COLUMN mobile_no TO contact_no;
ALTER TABLE human RENAME COLUMN hair_color TO hair_type;
ALTER TABLE human RENAME COLUMN inspiration TO inspiration_person;
ALTER TABLE human RENAME COLUMN pan_no TO pancard_no;
ALTER TABLE human RENAME COLUMN age TO pet_name;
ALTER TABLE human MODIFY COLUMN gender varchar(10);
ALTER TABLE human MODIFY COLUMN year_of_birth int;
ALTER TABLE human MODIFY COLUMN marital_status varchar(10);
select * from human;
DESCRIBE human;
ALTER TABLE majestic ADD COLUMN no_of_shops int;
ALTER TABLE majestic ADD COLUMN age int;
ALTER TABLE majestic ADD COLUMN features varchar(20);
ALTER TABLE majestic ADD COLUMN significance varchar(30);
ALTER TABLE majestic ADD COLUMN mythology boolean;
ALTER TABLE majestic ADD COLUMN protection_status boolean;
ALTER TABLE majestic ADD COLUMN no_of_visitors int;
ALTER TABLE majestic ADD COLUMN photography boolean;
ALTER TABLE majestic ADD COLUMN availabiities varchar(20);
ALTER TABLE majestic ADD COLUMN description_info varchar(50);
ALTER TABLE majestic DROP COLUMN protection_status;
ALTER TABLE majestic DROP COLUMN cleaners;
ALTER TABLE majestic RENAME COLUMN destination TO location;
ALTER TABLE majestic RENAME COLUMN acers_of_majestric TO size;
ALTER TABLE majestic RENAME COLUMN color_of_bus TO bus_color;
ALTER TABLE majestic RENAME COLUMN no_of_shops TO shops_visited;
ALTER TABLE majestic RENAME COLUMN features TO help_center;
ALTER TABLE majestic MODIFY COLUMN shops_visited bigint;
ALTER TABLE majestic MODIFY COLUMN photography varchar(20);
ALTER TABLE majestic MODIFY COLUMN availabiities boolean;
select * from majestic;
DESCRIBE majestic;
ALTER TABLE malls ADD COLUMN city varchar(10);
ALTER TABLE malls ADD COLUMN country varchar(10);
ALTER TABLE malls ADD COLUMN size int;
ALTER TABLE malls ADD COLUMN major_stores int;
ALTER TABLE malls ADD COLUMN category varchar(20);
ALTER TABLE malls ADD COLUMN entertainment_options boolean;
ALTER TABLE malls ADD COLUMN dining_option boolean;
ALTER TABLE malls ADD COLUMN events_available boolean;
ALTER TABLE malls ADD COLUMN contact_number bigint;
ALTER TABLE malls ADD COLUMN website varchar(20);
ALTER TABLE malls DROP COLUMN saled_products;
ALTER TABLE malls DROP COLUMN new_products;
ALTER TABLE malls RENAME COLUMN branch_name To name_of_branch;
ALTER TABLE malls RENAME COLUMN country To located_country;
ALTER TABLE malls RENAME COLUMN contact_number To mobile_number;
ALTER TABLE malls RENAME COLUMN major_stores To stores;
ALTER TABLE malls MODIFY COLUMN website boolean;
ALTER TABLE malls MODIFY COLUMN size bigint;
ALTER TABLE malls MODIFY COLUMN no_of_branches bigint;
select * from malls;
DESCRIBE malls;
ALTER TABLE education ADD COLUMN system_id int;
ALTER TABLE education ADD COLUMN country_id int;
ALTER TABLE education ADD COLUMN official_language varchar(80);
ALTER TABLE education ADD COLUMN curriculam varchar(34);
ALTER TABLE education ADD COLUMN grading_scale varchar(76);
ALTER TABLE education ADD COLUMN acadamic_calender varchar(75);
ALTER TABLE education ADD COLUMN school_type varchar(80);
ALTER TABLE education ADD COLUMN last_updated int;
ALTER TABLE education ADD COLUMN contact_information varchar(40);
ALTER TABLE education ADD COLUMN notable_institutions varchar(30);
ALTER TABLE education ADD COLUMN education_reform varchar(60);
ALTER TABLE education ADD COLUMN  school_board varchar(35);
SELECT * FROM education;
ALTER TABLE education DROP COLUMN school_board;
ALTER TABLE education DROP COLUMN system_id;
ALTER TABLE education MODIFY COLUMN last_updated double;
ALTER TABLE education MODIFY COLUMN country_id float;
ALTER TABLE education MODIFY COLUMN school_type double;
ALTER TABLE education RENAME COLUMN school_type TO school_category;
ALTER TABLE education RENAME COLUMN grading_scale TO marks_state;
ALTER TABLE education RENAME COLUMN last_updated TO current_updated;
ALTER TABLE education RENAME COLUMN education_reform TO education_application;
ALTER TABLE education RENAME COLUMN contact_information TO contact_number;
DESC education;
ALTER TABLE river ADD COLUMN river_source varchar(10);
ALTER TABLE river ADD COLUMN country varchar(10);
ALTER TABLE river ADD COLUMN tributaries boolean;
ALTER TABLE river ADD COLUMN flow_rate int;
ALTER TABLE river ADD COLUMN delta varchar(20);
ALTER TABLE river ADD COLUMN navigation varchar(30);
ALTER TABLE river ADD COLUMN ecology varchar(20);
ALTER TABLE river ADD COLUMN historical_significance boolean;
ALTER TABLE river ADD COLUMN dam boolean;
ALTER TABLE river ADD COLUMN conservation_status boolean;
ALTER TABLE river DROP COLUMN water_flow;
ALTER TABLE river DROP COLUMN boat_sailorname;
ALTER TABLE river RENAME COLUMN no_of_boats To boats_available;
ALTER TABLE river RENAME COLUMN acers To length;
ALTER TABLE river RENAME COLUMN tributaries To tributary;
ALTER TABLE river RENAME COLUMN navigation To root;
ALTER TABLE river RENAME COLUMN root To navigation;
ALTER TABLE river MODIFY COLUMN flow_rate double;
ALTER TABLE river MODIFY COLUMN no_of_aqualife double;
ALTER TABLE river MODIFY COLUMN boats_available boolean;
select * from river;
