use sahana;
UPDATE bengalore SET no_of_malls = 30, no_of_places = 153, places_name = 'GT', no_of_busstops= 75, city_buses = 70 WHERE no_of_malls = 30 AND no_of_places = 80 AND places_name = 'Lalbagh Botanical Garden' AND no_of_busstops = 150 AND city_buses = 400;
UPDATE bengalore SET no_of_malls = 75, no_of_places = 175, places_name = 'Garuda', no_of_busstops= 145, city_buses = 200 WHERE no_of_malls = 55 AND no_of_places = 105 AND places_name = 'orion' AND no_of_busstops = 225 AND city_buses = 550;
UPDATE bengalore SET no_of_malls = 50, no_of_places = 100, places_name = 'lullu', no_of_busstops= 205, city_buses = 560 WHERE no_of_malls = 40 AND no_of_places = 90 AND places_name = 'Wonderla' AND no_of_busstops = 180 AND city_buses = 450;
UPDATE bengalore SET no_of_malls = 65, no_of_places = 125, places_name = 'Wonderla', no_of_busstops= 208, city_buses = 90 WHERE no_of_malls = 35 AND no_of_places = 75 AND places_name = 'Koramangala' AND no_of_busstops = 160 AND city_buses = 420;
UPDATE bengalore SET no_of_malls = 78, no_of_places = 200, places_name = 'Commercial Street', no_of_busstops= 325, city_buses = 330 WHERE no_of_malls = 50 AND no_of_places = 100 AND places_name = 'UB City' AND no_of_busstops = 200 AND city_buses = 500;
UPDATE bengalore SET no_of_malls = 80, no_of_places = 255, places_name = 'Malleswaram', no_of_busstops= 105, city_buses = 360 WHERE no_of_malls = 40 AND no_of_places = 90 AND places_name = 'Brigade Road' AND no_of_busstops = 180 AND city_buses = 450;
UPDATE bengalore SET no_of_malls = 85, no_of_places = 205, places_name = 'MG Road', no_of_busstops= 315, city_buses = 100 WHERE no_of_malls = 30 AND no_of_places = 80 AND places_name = 'Commercial Street' AND no_of_busstops = 150 AND city_buses = 400;
UPDATE bengalore SET no_of_malls = 20, no_of_places = 95, places_name = 'UB City', no_of_busstops= 25, city_buses = 30 WHERE no_of_malls = 60 AND no_of_places = 120 AND places_name = 'ISKCON Temple' AND no_of_busstops = 220 AND city_buses = 550;
UPDATE bengalore SET no_of_malls = 15, no_of_places = 45, places_name = 'ISKCON Temple', no_of_busstops= 95, city_buses = 300 WHERE no_of_malls = 35 AND no_of_places = 75 AND places_name = 'UB City' AND no_of_busstops = 160 AND city_buses = 420;
SELECT * FROM bengalore;
UPDATE bio SET full_name = 'Punith',email = 'punith@gmail.com', address = 'Mysure', age = 29, blood_group = 'A+' WHERE full_name = 'Sanvi ganesh' AND email = 'sanvi@gmail.com';
UPDATE bio SET full_name = 'sandhya',email = 'sandhya@gmail.com', address = 'Hassan', age = 22, blood_group = 'B+' WHERE full_name = 'Sakshi ganesh' AND email = 'sakshi@gmail.com';
UPDATE bio SET full_name = 'Varsha',email = 'varsha@gmail.com', address = 'bengalore', age = 10, blood_group = '0+' WHERE full_name = 'Vaishnavi' AND email = 'vaishu@gmail.com';
UPDATE bio SET full_name = 'Priyanka',email = 'priya@gmail.com', address = 'Udupi', age = 26, blood_group = 'o-' WHERE full_name = 'Sahana' AND email = 'sahana@gmail.com';
UPDATE bio SET full_name = 'Kavya',email = 'kavya@gmail.com', address = 'Kolar', age = 16, blood_group = 'A-' WHERE full_name = 'Arjun' AND email = 'arjun@gmail.com';
SELECT * FROM bio;
UPDATE sports SET player_age= 30,sports_type = 4,player_prcatice = 3,attend_nationals = 5,Sports_name= 'olympic'WHERE player_name = 'John Doe';
UPDATE sports SET player_age= 25,sports_type = 1,player_prcatice = 5,attend_nationals = 2,Sports_name= 'Wight'WHERE player_name = 'Alice smith';
UPDATE sports SET player_age= 40,sports_type = 2,player_prcatice = 5,attend_nationals = 6,Sports_name= 'Volleyball'WHERE player_name = 'William Clark';
UPDATE sports SET player_age= 35,sports_type = 5,player_prcatice = 6,attend_nationals = 8,Sports_name= 'cricket'WHERE player_name = 'Bob Johnson';
UPDATE sports SET player_age= 32,sports_type = 3,player_prcatice = 8,attend_nationals = 4,Sports_name= 'Tennis'WHERE player_name = 'Sophia';
SELECT * FROM sports;
UPDATE railway_station SET platform_count = 6,station_manager_name = 'Bob',station_type = 'Major',location = 'pune',parking_facilities = 'Yes' WHERE station_name = 'Central'AND station_code = 1313;
UPDATE railway_station SET platform_count = 3,station_manager_name = 'Sanvi',station_type = 'Minor',location = 'SKP',parking_facilities = 'NO' WHERE station_name = 'WestJunction'AND station_code = 202;
UPDATE railway_station SET platform_count = 8,station_manager_name = 'Sahana',station_type = 'junction',location = 'Hassan',parking_facilities = 'Yes' WHERE station_name = 'North'AND station_code = 303;
UPDATE railway_station SET platform_count = 4,station_manager_name = 'Aishu',station_type = 'Major',location = 'Arsikere',parking_facilities = 'Yes' WHERE station_name = 'South'AND station_code = 505;
UPDATE railway_station SET platform_count = 3,station_manager_name = 'Kruthi',station_type = 'Minor',location = 'Karwar',parking_facilities = 'No' WHERE station_name = 'South'AND station_code = 1717;
SELECT * FROM railway_station;
UPDATE bottle SET material = 'Steel', shape = 'Square',capacity = 750,colour = 'Green',brand = 'Milton'WHERE shape = 'Round' AND length = 15;
UPDATE bottle SET material = 'Metal', shape = 'Round',capacity = 500,colour = 'Greay',brand = 'Cello'WHERE shape = 'Square' AND length = 12;
UPDATE bottle SET material = 'Plastic', shape = 'Cylinder',capacity = 250,colour = 'Red',brand = 'Python'WHERE shape = 'Square' AND length = 14;
UPDATE bottle SET material = 'Fibar', shape = 'Square',capacity = 1000,colour = 'Blue',brand = 'Milton'WHERE shape = 'Round' AND length = 8;
UPDATE bottle SET material = 'Steel', shape = 'Round',capacity = 500,colour = 'purple',brand = 'Cello'WHERE shape = 'cylinder' AND length = 20;
SELECT * FROM bottle;
UPDATE refrigerator SET capacity = 1250, cooling_system = 'Medium',internet_connectivity = 'No', warranty = 2, temperature_display = 'Analog' WHERE model = 'Abd173';
UPDATE refrigerator SET capacity = 1250, cooling_system = 'Medium',internet_connectivity = 'No', warranty = 2, temperature_display = 'Analog' WHERE model = 'Abd173';
UPDATE refrigerator SET capacity = 1250, cooling_system = 'Medium',internet_connectivity = 'No', warranty = 2, temperature_display = 'Analog' WHERE model = 'Abd173';
UPDATE refrigerator SET capacity = 1250, cooling_system = 'Medium',internet_connectivity = 'No', warranty = 2, temperature_display = 'Analog' WHERE model = 'Abd173';
UPDATE refrigerator SET capacity = 1250, cooling_system = 'Medium',internet_connectivity = 'No', warranty = 2, temperature_display = 'Analog' WHERE model = 'Abd173';
SELECT * FROM refrigerator;
UPDATE tickets SET depot_num = 2,depot_district = 'Bangalore',ticket_time = '09:30:00',ticket_language = 'Kannada',total_amount = 60 WHERE ticket_num = 1001;
UPDATE tickets SET depot_num = 3,depot_district = 'Belgam',ticket_time = '06:00:00',ticket_language = 'Hindi',total_amount = 100 WHERE ticket_num = 1002;
UPDATE tickets SET depot_num = 14,depot_district = 'Kolar',ticket_time = '11:40:00',ticket_language = 'English',total_amount = 250 WHERE ticket_num = 1003;
UPDATE tickets SET depot_num = 6,depot_district = 'Madkeri',ticket_time = '00:30:00',ticket_language = 'bengali',total_amount = 200 WHERE ticket_num = 1004;
UPDATE tickets SET depot_num = 9,depot_district = 'Bijapur',ticket_time = '01:30:00',ticket_language = 'Gujrathi',total_amount = 530 WHERE ticket_num = 1005;
SELECT * FROM tickets;
UPDATE oven SET price = 5999.99,capacity = 'Large',colour = 'Silver',power_source = 'Gas',energy_rating = 5 WHERE brand = 'Samsung' AND model = 'OVN-001';
UPDATE oven SET price = 7999.99,capacity = 'Medium',colour = 'Brown',power_source = 'Electric',energy_rating = 10 WHERE brand = 'LG' AND model = 'OVN-003';
UPDATE oven SET price = 9999.99,capacity = 'Large',colour = 'Red',power_source = 'Electric',energy_rating = 8 WHERE brand = 'Whirlpool' AND model = 'OVN-002';
UPDATE oven SET price = 6999.99,capacity = 'Extra Large',colour = 'blue',power_source = 'Gas',energy_rating = 5 WHERE brand = 'KitchenAid' AND model = 'OVN-004';
UPDATE oven SET price = 4999.99,capacity = 'Small',colour = 'Silver',power_source = 'Electric',energy_rating = 7 WHERE brand = 'GE' AND model = 'OVN-005';
SELECT * FROM oven;
UPDATE windows SET width = 72.3,height = 48.6,material = 'Vinyl',Style = 'Sliding',brand_name = 'XYZ Windows'WHERE window_security = 'Standard' AND weather_resistance = 'High' AND locking = 'keyed';
UPDATE windows SET width = 68.5,height = 52.0,material = 'Vinyl',Style = 'Casement',brand_name = 'ABC Windows'WHERE window_security = 'Enhanced' AND weather_resistance = 'low' AND locking = 'lever';
UPDATE windows SET width = 70.9,height = 42.8,material = 'Vinyl',Style = 'Sliding',brand_name = 'EFG Windows'WHERE window_security = 'Standard' AND weather_resistance = 'Medium' AND locking = 'keyed';
UPDATE windows SET width = 85.3,height = 32.9,material = 'Vinyl',Style = 'Awning',brand_name = 'SAM Windows'WHERE window_security = 'Enhanced' AND weather_resistance = 'High' AND locking = 'lever';
UPDATE windows SET width = 76.3,height = 57.8,material = 'Vinyl',Style = 'Sliding',brand_name = 'RST Windows'WHERE window_security = 'Standard' AND weather_resistance = 'Medium' AND locking = 'keyed';
SELECT * FROM windows;
UPDATE movie SET production = 'HMT Films',voice_dub = 'No',Hero = 'Jerry',visuals = 'Breathtaking',characters = 'Intriguing' WHERE director = 'Michael';
UPDATE movie SET production = 'Chintu films',voice_dub = 'Yes',Hero = 'Panda',visuals = 'Impressive',characters = 'Animy' WHERE director = 'Energetic';
UPDATE movie SET production = 'BTS Studios',voice_dub = 'Yes',Hero = 'Dora',visuals = 'Spectacular',characters = 'Compelling' WHERE director = 'Soulful';
UPDATE movie SET production = 'CN Films',voice_dub = 'No',Hero = 'Pinkpanther',visuals = 'Stunning',characters = 'Memorable' WHERE director = 'Upbeat';
UPDATE movie SET production = 'Pogo Films',voice_dub = 'Yes',Hero = 'Ninja',visuals = 'Gorgeous',characters = 'Emotional' WHERE director = 'Rhythmic';
SELECT * FROM movie;
Delete from tickets where ticket_num = 1006;
Delete from tickets where ticket_num = 1007;
Delete from tickets where ticket_num = 1008;
Delete from tickets where ticket_num = 1009;
Delete from tickets where ticket_num = 1010;
SELECT * FROM tickets;
Delete from bio where age = 10;
Delete from bio where age = 29;
Delete from bio where age = 30;
Delete from bio where age = 36;
Delete from bio where age = 25;
SELECT * FROM bio;
Delete from bengalore where no_of_malls = 65;
Delete from bengalore where no_of_malls = 85;
Delete from bengalore where no_of_malls = 80;
Delete from bengalore where no_of_malls = 78;
Delete from bengalore where no_of_malls = 70;
SELECT * FROM bengalore;
Delete from bottle where total_area = 105;
Delete from bottle where total_area = 60;
Delete from bottle where total_area = 98;
Delete from bottle where total_area = 160;
Delete from bottle where total_area = 112;
SELECT * FROM bottle;
Delete from movie where production = 'RST Studios';
Delete from movie where production = 'UVW Films';
Delete from movie where production = 'IJK Productions';
Delete from movie where production = 'EFG Films';
Delete from movie where production = 'RST Studios';
SELECT * FROM movie;
Delete from oven where model = 'OWN-020';
Delete from oven where model = 'OWN-019';
Delete from oven where model = 'OWN-018';
Delete from oven where model = 'OWN-017';
Delete from oven where model = 'OWN-016';
SELECT * FROM oven;
Delete from railway_station where station_code = 2020;
Delete from railway_station where station_code = 1919;
Delete from railway_station where station_code = 1818;
Delete from railway_station where station_code = 1515;
Delete from railway_station where station_code = 1616;
SELECT * FROM railway_station;
Delete from refrigerator where model = 'L927d';
Delete from refrigerator where model = 'Qs312';
Delete from refrigerator where model = 'HT9876';
Delete from refrigerator where model = 'Q24rf';
Delete from refrigerator where model = 'B34t5';
SELECT * FROM refrigerator;
Delete from sports where player_name = 'Amelia';
Delete from sports where player_name = 'Mia ';
Delete from sports where player_name = 'Daniel';
Delete from sports where player_name = 'Emily ';
Delete from sports where player_name = 'Jacob';
SELECT * FROM sports;
Delete from windows where width = 63.5 AND height = 46.6;
Delete from windows where width = 72.3 AND height = 48.6;
Delete from windows where width = 41.5 AND height = 40.5;
Delete from windows where width = 72.3 AND height = 48.6;
Delete from windows where width = 65.3 AND height = 47.2;
SELECT * FROM windows;